### ISSUE TITLE
Clearly indicate relationship between primary and dependent column(s)

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#953] opened 2013-04-17 19:11 UTC
Right now the user more or less has to remember the association between primary and dependent column. We need a visual indicator or label to show this relationship.

**Comment by alexsb** [comment] 2013-04-24 18:48
Related to #674 and #1140

**Comment by alexsb** [comment] 2013-06-17 16:08
This is a duplicate of the above issues.

**Closed as completed by alexsb** 2013-06-17 16:08 UTC
Labels: Important, StratomeX
