### ISSUE TITLE
Set default positions for StratomeX, TourGuide, etc

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1133] opened 2013-04-17 19:16 UTC
It would be good to have dedicated default positions for views. E.g., StratomeX should always open in the center, while Tourguide should always open at the side.

**Comment by sgratzl** [comment] 2013-04-17 19:16
I can't find a way, that Stratomex and other views opens at the center while Tourguide opens at the right side. 

Therefore I would open TourGuide in the center too, and if you moved it once to the right side it will be reopened there.

**Comment by alexsb** [comment] 2013-04-17 19:36
I updated this description. Is this what is meant? Is this a duplicate of #864

**Comment by sgratzl** [comment] 2013-06-17 10:03
can anyone (besides me) tries to check if it works now.

btw. the current solutions creates place holders for all views one the fly and there is a special issue with views that have multiple instances, where I need to use the `<viewid>:*` syntax

**Comment by mstreit** [comment] 2013-06-17 10:59
works for me. nice!

**Comment by alexsb** [comment] 2013-06-18 18:46
I've observed a problem with a pathway. Reproduce with latest GBM sample dataset:

Open LineUp via StratomeX. Open Pathway. Pathway is in same area as lineup. Once you've dragged pathway up and closed and reopened it again it behaves correctly. 

Other views work as expected (enRoute, PCs and table tested).

**Comment by mstreit** [comment] 2013-06-21 11:29
All three TourGuide instances appear as a main tab right next to StratomeX. I would expect them to be opened at the bottom.

**Comment by sgratzl** [comment] 2013-06-21 13:19
> That's really strange. It used to work already (see my comment above). I've already tried to clean the .caleydo folder as well as the launch config. Anything else I could try?

I don't know. Similarly I can't see any splash screen, and I don't know why

**Comment by ngehlenborg** [comment] 2013-06-21 13:22
> I don't know. Similarly I can't see any splash screen, and I don't know why

Because it is the Eclipse RCP ...

**Comment by mstreit** [comment] 2013-06-21 13:42
I still have Eclipse 4.2.1. Will try to update to 4.2.2. Maybe that solves some of these issues. I also still have the problem with the empty window that pops up during the startup phase.

**Comment by mstreit** [comment] 2013-06-21 13:48
Wow, the update to Eclipse RCP 4.2.2 solved my problem with the view positions.

**Closed as completed by mstreit** 2013-06-21 13:48 UTC
