### ISSUE TITLE
closing StratomeX causes FPSAnimator time out

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1475] opened 2013-07-14 16:47 UTC
The data set had been saved previously (all Kepler) with a StratomeX view that contains several stratifications (KIRC case study data set). 

The StratomeX view is not removed from the DVI. Only after closing the DVI the StratomeX view is gone.

``` java

FPSAnimator P1:Thread[main-null-Timer0,6,main]: Task[thread Thread[main-null-Timer0,6,main], stopped false, paused false shouldRun true, shouldStop false -- started true, animating true, paused false, drawable 5, drawablesEmpty false]
add data of Pathway Data
finishLifecycleAction(com.jogamp.opengl.util.FPSAnimator$4): ++++++ timeout reached ++++++ main
finishLifecycleAction(com.jogamp.opengl.util.FPSAnimator$4): OK false- pollPeriod 12, blocking true, waited 1001/1000 - main
 - com.jogamp.opengl.util.FPSAnimator[started true, animating true, paused true, drawable 5, totals[dt 0, frames 535, fps 0.0], modeBits 1, init'ed true, animThread Thread[main-null-Timer0,6,main], exclCtxThread false(null)]
java.lang.Exception: Stack trace
    at java.lang.Thread.dumpStack(Thread.java:1342)
    at com.jogamp.opengl.util.AnimatorBase.finishLifecycleAction(AnimatorBase.java:559)
    at com.jogamp.opengl.util.FPSAnimator.pause(FPSAnimator.java:317)
    at com.jogamp.opengl.util.AnimatorBase.remove(AnimatorBase.java:229)
    at org.caleydo.core.view.ViewManager.unregisterGLCanvas(ViewManager.java:162)
    at org.caleydo.core.view.ARcpGLViewPart$1.widgetDisposed(ARcpGLViewPart.java:70)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4166)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1470)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1308)
    at org.eclipse.swt.widgets.Control.release(Control.java:2861)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1311)
    at org.eclipse.swt.widgets.Control.release(Control.java:2861)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1311)
    at org.eclipse.swt.widgets.Control.release(Control.java:2861)
    at org.eclipse.swt.widgets.Widget.dispose(Widget.java:671)
    at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.disposeWidget(SWTPartRenderer.java:152)
    at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.disposeWidget(ContributedPartRenderer.java:273)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:899)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$3(PartRenderingEngine.java:828)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$8.run(PartRenderingEngine.java:823)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:808)
    at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.disposeWidget(ElementReferenceRenderer.java:109)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:899)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$3(PartRenderingEngine.java:828)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$8.run(PartRenderingEngine.java:823)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:808)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.handleEvent(PartRenderingEngine.java:153)
    at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:41)
    at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
    at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
    at org.eclipse.swt.widgets.Display.syncExec(Display.java:4650)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:205)
    at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
    at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
    at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
    at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
    at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:80)
    at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:58)
    at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
    at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setToBeRendered(UIElementImpl.java:290)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1160)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1095)
    at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.closePart(StackRenderer.java:1069)
    at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.access$5(StackRenderer.java:1051)
    at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer$11.close(StackRenderer.java:945)
    at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1833)
    at org.eclipse.swt.custom.CTabFolder$1.handleEvent(CTabFolder.java:283)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4166)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1474)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4012)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3651)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.caleydo.core.internal.Application.start(Application.java:84)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

!ENTRY StratomeX 1 0 2013-07-14 12:42:53.469
!MESSAGE Disposing view
destroy Heatmap
destroy Heatmap
destroy Histogram
destroy Heatmap
destroy Heatmap
destroy Heatmap
destroy Histogram
destroy Brick
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Histogram
destroy Brick
destroy Heatmap
destroy Brick Column
destroy Heatmap
destroy Histogram
destroy Heatmap
destroy Heatmap
destroy Heatmap
destroy Heatmap
destroy Heatmap
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Histogram
destroy Brick Column
destroy Brick
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Histogram
destroy Brick Column
destroy Histogram
destroy Heatmap
destroy Heatmap
destroy Brick
destroy Heatmap
destroy Brick
destroy Histogram
destroy Brick
destroy Heatmap
destroy Brick Column
destroy StratomeX
```

**Comment by ngehlenborg** [comment] 2013-07-14 16:55
Apparently this is only happening with the previously saved StratomeX. StratomeX views created in the same session don't seem to have this issue.

**Comment by sgratzl** [comment] 2013-07-14 18:17
I don't know whether this is really StraomeX specific, as I get this error all the time, when I'm opening a new view: see #1386 

I assume as we are still doing a lot of things within the OpenGL Thread, see #1406, the new jogl version complains that a maximum frame time was exceeded

**Comment by sgratzl** [comment] 2013-07-18 07:26
@ALL I have implemented an own FPSAnimator. Can everyone please test if he encounters some problems with it?

**Comment by mstreit** [comment] 2013-07-18 09:50
Seems to work. However, when playing around I got the following exception. If it's unrelated to this issue, then it can be extracted to a new one

```
!ENTRY org.caleydo.core.view.opengl.canvas.MyAnimator 4 0 2013-07-18 11:47:43.406
!MESSAGE display error: SWT-GLCanvas[Realized true,
    jogamp.opengl.x11.glx.X11OnscreenGLXDrawable,
    Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@1971261d,
    handle    0x7200002,
    Drawable size 1654x277,
    SWT size 1654x277]
!STACK 0
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:263)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:193)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:264)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:193)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:222)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView.display(GLTourGuideView.java:569)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:583)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:567)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1029)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:904)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:174)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by sgratzl** [comment] 2013-07-18 10:05
> However, when playing around I got the following exception

how did you get this error?

did you use some context menus?

**Comment by mstreit** [comment] 2013-07-18 12:29
After closing some views, sometimes Caleydo crashes silently on my machine. I also can't reproduce the error from above. It could be some issue with my ATI graphics card again. If the new animator works for the rest of the team, we can close the ticket.
@alexsb Please test on your linux machine.

**Comment by sgratzl** [comment] 2013-07-22 10:44
...

> @alexsb Please test on your linux machine.

**Comment by alexsb** [comment] 2013-07-22 15:39
No problems observed.

**Closed as completed by alexsb** 2013-07-22 15:39 UTC
Labels: Bug, DVI, Critical, StratomeX
