### ISSUE TITLE
support loading of full expression/methylation/RPPA/etc. matrices

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1334] opened 2013-06-25 15:06 UTC
This is important for instance for pathway mapping.
- [ ] display only "genes" used for clustering in heatmap bricks
- [ ] test if large data packages load on computers with "normal" amounts of memory
- [ ] build two sets of TCGA data packages (full data, selected data)

**Comment by alexsb** [comment] 2013-06-25 15:38
Duplicate of #1216 (scheduled for 3.1)

**Closed as completed by alexsb** 2013-06-25 15:38 UTC
Labels: Enhancement, Pathway, Important, StratomeX
