### ISSUE TITLE
stratifications in StratomeX view from external datasets (categorical nominal loaded file) are not saved in project

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1368] opened 2013-07-01 00:30 UTC
I had added some additional categorical nominal stratifications from a file as a new datatype and after saving and re-loading the project, they were no longer in the StratomeX view, even though the mutation stratifications that had been in the same view, were still there.

**Comment by alexsb** [comment] 2013-07-01 00:51
duplicate of #1179

**Closed as completed by alexsb** 2013-07-01 00:51 UTC
Labels: Bug, StratomeX
