### ISSUE TITLE
color and histogram mismatches for mutations

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1327] opened 2013-06-24 16:54 UTC
Compare colors in header brick histogram and bricks - two different reds.

Compare header bricks histogram and main histogram - two different histograms? Color swap?

![screen shot 2013-06-24 at 12 52 08 pm](https://f.cloud.github.com/assets/1216518/696753/979d3338-dcee-11e2-842d-673ab7a12f5c.png)

**Comment by ngehlenborg** [comment] 2013-06-24 16:56
Hm. Apparently I had managed to select two columns at the same time, the data set info is for a column next to the mutation column even though the mutation column is selected. Here is an updated screenshot.

![screen shot 2013-06-24 at 12 54 53 pm](https://f.cloud.github.com/assets/1216518/696760/fc302f6c-dcee-11e2-9d74-08e19856d4d7.png)

**Comment by alexsb** [comment] 2013-06-24 17:33
Duplicate of #1328

**Closed as completed by alexsb** 2013-06-24 17:33 UTC
