### ISSUE TITLE
Censoring in KM

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#670] opened 2013-04-17 19:03 UTC

**Comment by alexsb** [comment] 2013-04-17 19:03
There needs to be a visual encoding for censoring information (e.g. patient died from other causes, moved away, etc.).
We also need to parse and store censoring information.

**Comment by alexsb** [comment] 2013-06-17 15:13
@ngehlenborg will investigate details on the data format and how to visually encode and report here

**Comment by ngehlenborg** [comment] 2013-06-17 15:25
Example on TCGA data: http://dx.doi.org/10.7908/C17H1GGV

**Comment by ngehlenborg** [comment] 2013-06-17 15:56
It looks like the daystolastknownalive (https://cdebrowser.nci.nih.gov/CDEBrowser/search?elementDetails=9&FirstTimer=0&PageId=ElementDetailsGroup&publicId=2975724&version=1.0) variable can be used for censoring. I will confirm this.

**Comment by ngehlenborg** [comment] 2013-06-17 19:57
It is indeed another variable, but not daystolastknowalive. Instead, the Firehose folks are using the daystolastfollowup variable to determine when to censor someone.

This means that the Kaplan-Meier plot basically requires a pair of variables, one for survival and one for censoring. It will work with only the survival variable but the calculations (log-rank test) will be inaccurate.

**Comment by ngehlenborg** [comment] 2013-06-17 20:41
_daystodeath_ and _daystolastfollowup_ are mutually exclusive. Patients have a value only for one or the other, but never both (as far as manual inspection of a couple of hundreds of cases tells me).
We need to order all patients by the value in the union of _daystodeath_ and _daystolastfollowup_. When you see a patient die, you need to reduce the count (i.e. step down in the plot) and if a patient was last followed up X days ago, you need to make a "+" at X days.

The censoring simply indicates that a patient's status was not known after X days, because we don't know for sure that the patient was alive between X+1 days and now.

But in any case: starting from a time point t, we know that after x days, N patients are alive (because their death or last follow up is > x), M patients are dead (because their death was < x) and L patients are in limbo (because their last follow up was < x and they are not confirmed dead). As soon as a patient is in limbo we need to censor them: http://www.cancerguide.org/scurve_km.html

(I am not even sure if Firehose is using the correct variable: https://cdebrowser.nci.nih.gov/CDEBrowser/search?elementDetails=9&FirstTimer=0&PageId=ElementDetailsGroup&publicId=2897022&version=1.0)

**Comment by alexsb** [comment] 2013-06-17 20:52
One way to implement this would be to provide metadata on a per column base. Generally speaking we could add a dependency to a column. The main column could be the days to death, the dependent column could be the censoring. 

The KM plot could, if provided with such a column, look up the dependent column by itself. If no column is provided the view could ask for it or simply just display the original column

**Comment by ngehlenborg** [comment] 2013-06-20 20:33
How do we want to proceed with this? Shall we discuss this next Monday?

**Closed as completed** 2018-06-26 10:47 UTC
Labels: Enhancement, StratomeX
