### ISSUE TITLE
Text renderer artefacts

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#931] opened 2013-04-17 19:10 UTC
see screenshot.
this is non deterministic but occurs regularly

**Comment by sgratzl** [comment] 2013-05-24 08:05
observations: 
- its getting worse if both tourguide and stratomex are visible
- if I periodically force to update the whole bitmap texture then for a single frame the text looks ok
- tourguide text renderer as well as the stratomex renderer uses the same texture id but of couse different gl contexts
- tour guide updates its text texture more frequent than stratomex because of cleaning up every 100 draws and drawing a lot of text
- if I force to update the whole texture before I draw something in stratomex it looks ok
- if I reduce the frame rate to e.g 10 artifacts disappear

theory:
 somehow the different textures use the same space or it seems to be that the texture update from tour guide will update the texture data from stratomex 

solution?

**Comment by sgratzl** [comment] 2013-05-27 14:53
observations: 
- it's getting better if you explicitly unbound the texture after rendering and bind it fresh before rendering -> reduces between view errors
- disabling mip mapping will increase readability if you have have a large text size chosen as your basic font (given 24 point, rendered as 10-12pt)
- you somehow loose characters if have a visible brick

theory:
given: 
- Bricks are rendered with display lists
- the text renderer is lazy, meaning that if a character is not yet in the texture it will be automatically uploaded

the theory is now that during the creation of the display list a character has to be uploaded. Therefore the texture of the text renderer will be updated. This update is recorded in the display list and will be repeated every time when the display list is executed, even though the update should only be executed once.

In a later step (outside of the display list) another character has to be uploaded (let use the character P). So we have following scenario: 
1. upload character P once at position XY
2. render P using position XY
3. execute the recorded display list -> part of it: update texture
4. NEXT FRAME
5. don't upload character P again, as we already have it uploaded
6. render P using position XY -> **nothing** will be rendered as my assumption that it is already on the graphics card is wrong, as during 3. the "old" texture state was recreated
   ...

solution: 
1. don't use a text renderer for both display lists and not display lists or be sure that during recording of the display list everything is already in the text renderer cache. 

changes of the text renderer:
1. the original text renderer is quite greedy, that means every 100 calls it will cleanup not used characters -> change to cleanup right before the underlying texture needs to be expanded
2. every change was directly uploaded to the graphics card -> minimize the upload calls by just once right before rendering
3. starting from scratch -> changed such that all characters between '!' and '~' will be prefilled to have the most common characters already in the cache

**Comment by mstreit** [comment] 2013-06-03 16:40
I guess we can close the issue, right?

**Comment by cpartl** [comment] 2013-06-04 09:04
I do still experience text rendering problems, e.g., the list of stratifications in tourguide shows artifacts when selecting a stratification for preview. Although overall the problems occur less frequently.

**Comment by sgratzl** [comment] 2013-06-04 12:44
> I do still experience text rendering problems, e.g., the list of stratifications in tourguide shows artifacts when selecting a stratification for preview. Although overall the problems occur less frequently.

I don't have any problems on my windows machine. Can you attach a screenshot?

**Comment by cpartl** [comment] 2013-06-04 13:51
![text_bug_tourguide](https://f.cloud.github.com/assets/4134949/605772/c265ecc6-cd1d-11e2-823d-c9ba60abf815.png)

**Comment by sgratzl** [comment] 2013-06-05 08:06
that seems to be a different kind of rendering artifacts as it seems that for all rows you have the same text (rank, stratification)

can you try to visualize the render cache (uncomment GLElement 209ff) and check if this has something to do with it

In addition is this bug reproduceable and if yes how + is there a way that it will disappear if you do some action?

**Comment by cpartl** [comment] 2013-06-05 08:36
![text_bug_cache](https://f.cloud.github.com/assets/4134949/610571/757235fe-cdb9-11e2-9dc9-ae790b69b511.png)
The text seems to be wrong when it is not in the cache. After a little delay the text is in the cache and it gets displayed corretly. 
Here is another issue in StratomeX:
![text_bug_stratomex](https://f.cloud.github.com/assets/4134949/610598/198a997e-cdba-11e2-898d-fe58bb0f8f6f.png)

**Comment by sgratzl** [comment] 2013-06-05 09:02
both bugs are really weired:

in the first screenshot the same text is rendered multiple times or really all entries have the same value. Which is unlikely as after a while, when the caching starts, it looks ok. Especially as there is no entry: 2 CNMF Clustering | 112 | 1 <- should be 2

in the second screenshots parts are missing. I mean the parts are at the right position. It's unlikely that they were manually cut away (the implemented wrapping technique wouldn't cut out "tion"). It can't be just the text renderer as only some instances of e.g. the letter "e" were rendered.

to be honest I have no idea

**Comment by sgratzl** [comment] 2013-06-17 12:39
> in the first screenshot the same text is rendered multiple times or really all entries have the same value. Which is unlikely as after a while, when the caching starts, it looks ok. Especially as there is no entry: 2 CNMF Clustering | 112 | 1 <- should be 2

seems to be related that Vertex Arrays are used, if `useVertexArrays(false)` is used, then the bug disappears

**Comment by sgratzl** [comment] 2013-06-18 06:33
afik is works for everyone one -> closing

**Closed as completed by sgratzl** 2013-06-18 06:33 UTC
Labels: Critical
