### ISSUE TITLE
The width of the histogram should be same as the dataset info view width

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1387] opened 2013-07-03 13:33 UTC
At the moment the histogram is larger than the info view

**Comment by mstreit** [comment] 2013-07-03 13:34
![490eaa32-e34f-11e2-8740-a77398db7482](https://f.cloud.github.com/assets/4129755/743312/3abb46e8-e3e5-11e2-9eb4-855a528622f4.png)

**Comment by alexsb** [comment] 2013-07-03 13:35
Duplicate of / related to #1379

**Comment by mstreit** [comment] 2013-07-03 14:16
I think that's not a duplicate, but let's see.

**Comment by alexsb** [comment] 2013-07-03 21:58
It's not a duplicate :)

**Closed as completed** 2013-07-03 22:24 UTC
