### ISSUE TITLE
NPE in updatePathwayPortals

### ISSUE THREAD

**Issue by dkalkofen** [Caleydo/caleydo#1124] opened 2013-04-17 19:16 UTC
this one is really difficult to trigger, but appeared on my system after several path selections 
java.lang.NullPointerException
    at org.jgrapht.Graphs.getPathVertexList(Unknown Source)
    at org.caleydo.datadomain.pathway.graph.PathwayPath.getNodes(PathwayPath.java:60)
    at org.caleydo.view.subgraph.GLSubGraph.updatePathwayPortals(GLSubGraph.java:1114)
    at org.caleydo.view.subgraph.GLSubGraph.updateAugmentation(GLSubGraph.java:761)
    at org.caleydo.view.subgraph.GLSubGraph.display(GLSubGraph.java:798)

**Comment by cpartl** [comment] 2013-10-09 10:09
I was able to reproduce this error once, but could not reproduce it anymore since of that.
I think it might have to do with some corrupt path state that is caused in very special cases when selecting in context paths. Might be related to #1089. Moving to 3.1.1

**Comment by mstreit** [comment] 2013-10-28 14:46
Cannot reproduce. Re-open if observed again.

**Closed as completed** 2013-10-28 14:46 UTC
Labels: Entourage
