### ISSUE TITLE
resizing of the VisBricks view leads to incorrect scaling of the bricks

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#514] opened 2013-04-17 18:57 UTC
When I resize the VisBricks view, for instance by double-clicking the tab of the view (which in my case makes the view only wider but not higher), the height of the dimension groups seems to be calculated incorrectly. The bricks are scaled like the changed in view size is proportional along both axes, even though it is not.

New dimension groups that are added after the resize are scaled correctly and existing bricks can be refreshed and scaled to the correct size by switching the visualization type (doesn't work for the summary brick though).

**Comment by alexsb** [comment] 2013-04-17 18:57
duplicate of 683

**Closed as completed by alexsb** 2013-04-17 18:57 UTC
